version: '3.8'

services:
  db:
    image: mysql:8.0  # MySQL 8.0 이미지 사용
    container_name: flask_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # 루트 사용자 비밀번호
      MYSQL_DATABASE: flask_app           # 기본 데이터베이스
      MYSQL_USER: banbbang             # 사용자 이름
      MYSQL_PASSWORD: 1234      # 사용자 비밀번호
    ports:
      - "3306:3306"  # 호스트의 3306 포트를 컨테이너에 연결
    volumes:
      - db_data:/var/lib/mysql  # MySQL 데이터가 저장될 볼륨
    networks:
      - flask_network

  flask:
    build: .
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"  # Flask 앱의 5000 포트를 컨테이너와 연결
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://banbbang:1234@db/flask_app
    depends_on:
      - db
    networks:
      - flask_network

volumes:
  db_data:

networks:
  flask_network:
